### ISSUE TITLE
Weights question

### ISSUE THREAD

**Issue by JoeyFaulkner** [mrmaxent/maxnet#10]
Hi there!

just a question regarding this implementation of maxnet regarding the weights: in this package the weights are passed to glmnet with `weight=1` when `y=1` and `weight=100` when `y=0`, however in the implementation of glmnet that this uses, the only part of the code where this weight is explicitly used is (as far as I can see)

`if(!missing(weights)) y=y*weights`, 
so isn't this just equivalent to setting weight=1 for both y=1 and y=0 and not getting the benefit of infinitely weighted regression of Fithian & Hastie (2012)? I can see also that it changes the value of the regularization term but since there is a gridsearch on that parameter anyway this shouldnt have an actual effect right?

I'm sure I'm missing something crucial here, but would be interested in your feedback.

Thanks!

**Comment by mrmaxent** [comment]
If you try changing maxnet so that it passes weight=1 for both y=0 and y=1, the results are quite different, especially if the number of background points is small.  (Having many background points gives the same effect as up-weighting.)  So, glmnet must be using the weights elsewhere in its code, not just in that line from lognet that you quote.  I think the weights are used in its deviance calculations.
