### ISSUE TITLE
Error in maxnet function

### ISSUE THREAD

**Issue by Euconnus** [mrmaxent/maxnet#9]
Hello all,

Every time I try to run the **maxnet** function, I get this error message :

>  Error in seq.default(min, max, length = nknots) : 
>   'from' must be a finite number 

I tried with multiple, verified arguments (both the presence/absence data and the background points) and I always have this same issue. Does anyone have an idea ?

**Comment by Gavish-Yoni** [comment]
I got the same error, when trying to use ENMEvaluate
I've tracked it down to the function ENMEvaluate::modelTune.maxnet. 
In my code it happened since  the 'data' argument (a matrix or data frame of predictor variables) when calling maxnet had 0 rows. 
For me it happened since I wanted to use method = "user", but with  no cross validation (nk= 1).
Hope it helps
Maybe its worth adding an error message  to maxnet::maxnet if nrow(data) == 0,

**Comment by nesmonde** [comment]
Hi, 

I'm having the same issue with the maxnet function - did you get it sorted?

**Comment by Gavish-Yoni** [comment]
Sorry, I haven't sorted it. I wrote my own wrapper functions around maxnet.

**Comment by cdkuempel** [comment]
For the maxnet function - I was getting this error when there was an NA value in one of my environmental variables. Once the NA was removed it worked. Hope that helps!

**Comment by mrmaxent** [comment]
Closing this issue, as maxnet now checks for NA values in the enviromental variables.
